/**
 * Remote Chat Integration Service
 * 
 * Bridges the remote message polling system with the local chat interface
 * Handles message routing and synchronization between remote and local modes
 */

import { remoteServiceManager } from './remoteServiceManager';
import { Message } from '../types/chat';

export interface RemoteChatIntegrationConfig {
  onRemoteMessage: (message: Message) => void;
  onRemoteResponse: (response: Message) => void;
  onStatusChange: (status: string) => void;
}

export class RemoteChatIntegration {
  private config: RemoteChatIntegrationConfig;
  private isActive = false;
  private statusCheckInterval?: NodeJS.Timeout;
  private messageCheckInterval?: NodeJS.Timeout;
  private lastProcessedMessageId?: string;

  constructor(config: RemoteChatIntegrationConfig) {
    this.config = config;
  }

  /**
   * Start monitoring for remote messages
   */
  async start(): Promise<void> {
    if (this.isActive) return;

    console.log('Starting remote chat integration...');
    this.isActive = true;

    // Start monitoring service status
    this.statusCheckInterval = setInterval(() => {
      this.checkServiceStatus();
    }, 2000);

    // Start checking for processed messages
    this.messageCheckInterval = setInterval(() => {
      this.checkForProcessedMessages();
    }, 1000);

    this.config.onStatusChange('Remote chat integration started');
  }

  /**
   * Stop monitoring
   */
  async stop(): Promise<void> {
    if (!this.isActive) return;

    console.log('Stopping remote chat integration...');
    this.isActive = false;

    if (this.statusCheckInterval) {
      clearInterval(this.statusCheckInterval);
      this.statusCheckInterval = undefined;
    }

    if (this.messageCheckInterval) {
      clearInterval(this.messageCheckInterval);
      this.messageCheckInterval = undefined;
    }

    this.config.onStatusChange('Remote chat integration stopped');
  }

  /**
   * Check service status and update UI accordingly
   */
  private checkServiceStatus(): void {
    if (!this.isActive) return;

    try {
      const status = remoteServiceManager.getStatus();
      
      if (status.isRunning && status.pollerStatus.isPolling) {
        this.config.onStatusChange('Remote service active');
      } else if (status.isRunning) {
        this.config.onStatusChange('Remote service starting...');
      } else {
        this.config.onStatusChange('Remote service offline');
      }
    } catch (error) {
      console.error('Failed to check service status:', error);
      this.config.onStatusChange('Service status check failed');
    }
  }

  /**
   * Check for newly processed messages from remote
   * This is a simplified implementation - in a real system, you'd want to
   * integrate more directly with the Supabase real-time subscriptions
   */
  private async checkForProcessedMessages(): Promise<void> {
    if (!this.isActive) return;

    try {
      const status = remoteServiceManager.getStatus();
      
      // Check if there are active streams (messages being processed)
      if (status.processorStatus.activeStreams.length > 0) {
        // Simulate receiving a remote message
        // In a real implementation, this would come from Supabase subscriptions
        this.simulateRemoteMessage();
      }
    } catch (error) {
      console.error('Failed to check for processed messages:', error);
    }
  }

  /**
   * Simulate receiving a remote message
   * This is a placeholder - in the real implementation, messages would come
   * from Supabase real-time subscriptions or polling
   */
  private simulateRemoteMessage(): void {
    // This is just for demonstration - remove in production
    const now = Date.now();
    if (this.lastProcessedMessageId && (now - parseInt(this.lastProcessedMessageId)) < 30000) {
      return; // Don't spam messages
    }

    this.lastProcessedMessageId = now.toString();

    const remoteMessage: Message = {
      id: `remote-incoming-${now}`,
      content: '🌐 Remote message received and being processed...',
      role: 'user',
      timestamp: new Date(),
      isRemote: true
    };

    this.config.onRemoteMessage(remoteMessage);

    // Simulate a response after a delay
    setTimeout(() => {
      const responseMessage: Message = {
        id: `remote-response-${now}`,
        content: '✅ Remote message processed successfully! This response was generated by your local Ally system and streamed back to the remote interface.',
        role: 'assistant',
        timestamp: new Date(),
        isRemote: true
      };

      this.config.onRemoteResponse(responseMessage);
    }, 3000);
  }

  /**
   * Send a message to the remote system
   * In remote mode, this would typically be handled by the web interface
   */
  async sendToRemote(content: string): Promise<void> {
    if (!this.isActive) {
      throw new Error('Remote chat integration not active');
    }

    // In a real implementation, this would send the message to Supabase
    // For now, we'll just create a local representation
    const outgoingMessage: Message = {
      id: `remote-outgoing-${Date.now()}`,
      content: `🌐 Sending to remote: ${content}`,
      role: 'user',
      timestamp: new Date(),
      isRemote: true
    };

    this.config.onRemoteMessage(outgoingMessage);
  }

  /**
   * Get current integration status
   */
  getStatus(): {
    isActive: boolean;
    serviceStatus: any;
    lastMessageId?: string;
  } {
    return {
      isActive: this.isActive,
      serviceStatus: remoteServiceManager.getStatus(),
      lastMessageId: this.lastProcessedMessageId
    };
  }
}

// Singleton instance
let remoteChatIntegration: RemoteChatIntegration | null = null;

export function createRemoteChatIntegration(config: RemoteChatIntegrationConfig): RemoteChatIntegration {
  if (remoteChatIntegration) {
    remoteChatIntegration.stop();
  }
  
  remoteChatIntegration = new RemoteChatIntegration(config);
  return remoteChatIntegration;
}

export function getRemoteChatIntegration(): RemoteChatIntegration | null {
  return remoteChatIntegration;
}