/**
 * Chat Sync Dashboard Component
 * 
 * Displays comprehensive sync status, statistics, and controls
 * Shows bidirectional sync status and real-time streaming activity
 */

import React, { useState } from 'react';
import { UnifiedSyncStatus } from '../services/unifiedChatSyncManager';
import { LocalChatSession } from '../services/bidirectionalChatSync';
import RealTimeStreamingIndicator from './RealTimeStreamingIndicator';

interface ChatSyncDashboardProps {
  status: UnifiedSyncStatus | null;
  localSessions: LocalChatSession[];
  streamingMessages: any[];
  statistics: any;
  errors: string[];
  isActive: boolean;
  isLoading: boolean;
  canSync: boolean;
  onStart: () => Promise<void>;
  onStop: () => Promise<void>;
  onForceSyncNow: () => Promise<void>;
  onTestConnectivity: () => Promise<any>;
  onClearErrors: () => void;
  onSimulateStream?: (messageId: string, content: string) => Promise<void>;
  className?: string;
}

export const ChatSyncDashboard: React.FC<ChatSyncDashboardProps> = ({
  status,
  localSessions,
  streamingMessages,
  statistics,
  errors,
  isActive,
  isLoading,
  canSync,
  onStart,
  onStop,
  onForceSyncNow,
  onTestConnectivity,
  onClearErrors,
  onSimulateStream,
  className = ''
}) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'sessions' | 'streaming' | 'logs'>('overview');
  const [connectivityResult, setConnectivityResult] = useState<any>(null);
  const [testingConnectivity, setTestingConnectivity] = useState(false);

  const handleTestConnectivity = async () => {
    setTestingConnectivity(true);
    try {
      const result = await onTestConnectivity();
      setConnectivityResult(result);
    } catch (error) {
      setConnectivityResult({
        syncConnected: false,
        streamingConnected: false,
        errors: [`Test failed: ${error instanceof Error ? error.message : 'Unknown error'}`]
      });
    } finally {
      setTestingConnectivity(false);
    }
  };

  const handleSimulateStream = async () => {
    if (onSimulateStream) {
      const messageId = `test-${Date.now()}`;
      const content = "This is a simulated streaming response to demonstrate real-time message processing. The text appears chunk by chunk as if it's being generated by an AI assistant in real-time.";
      await onSimulateStream(messageId, content);
    }
  };

  const formatTimestamp = (timestamp: number) => {
    if (!timestamp) return 'Never';
    return new Date(timestamp).toLocaleTimeString();
  };

  const formatDuration = (ms: number) => {
    if (ms < 1000) return `${ms}ms`;
    if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
    return `${(ms / 60000).toFixed(1)}m`;
  };

  return (
    <div className={`chat-sync-dashboard ${className}`}>
      {/* Header */}
      <div className="dashboard-header">
        <div className="header-title">
          <h3>Chat Sync Dashboard</h3>
          <div className={`sync-status ${isActive ? 'active' : 'inactive'}`}>
            <div className="status-dot" />
            <span>{isActive ? 'Active' : 'Inactive'}</span>
          </div>
        </div>
        
        <div className="header-controls">
          {canSync && (
            <>
              {!isActive ? (
                <button 
                  onClick={onStart} 
                  disabled={isLoading}
                  className="btn btn-primary"
                >
                  {isLoading ? 'Starting...' : 'Start Sync'}
                </button>
              ) : (
                <button 
                  onClick={onStop} 
                  disabled={isLoading}
                  className="btn btn-secondary"
                >
                  {isLoading ? 'Stopping...' : 'Stop Sync'}
                </button>
              )}
              
              {isActive && (
                <button 
                  onClick={onForceSyncNow} 
                  disabled={isLoading}
                  className="btn btn-accent"
                >
                  Force Sync
                </button>
              )}
            </>
          )}
          
          <button 
            onClick={handleTestConnectivity} 
            disabled={testingConnectivity}
            className="btn btn-outline"
          >
            {testingConnectivity ? 'Testing...' : 'Test Connection'}
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="dashboard-tabs">
        {['overview', 'sessions', 'streaming', 'logs'].map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab as any)}
            className={`tab ${activeTab === tab ? 'active' : ''}`}
          >
            {tab.charAt(0).toUpperCase() + tab.slice(1)}
            {tab === 'logs' && errors.length > 0 && (
              <span className="error-badge">{errors.length}</span>
            )}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="tab-content">
        {activeTab === 'overview' && (
          <div className="overview-tab">
            {/* Status Cards */}
            <div className="status-cards">
              <div className="status-card">
                <div className="card-header">Sync Status</div>
                <div className="card-content">
                  <div className="status-item">
                    <span>Active:</span>
                    <span className={status?.sync.isActive ? 'text-success' : 'text-error'}>
                      {status?.sync.isActive ? 'Yes' : 'No'}
                    </span>
                  </div>
                  <div className="status-item">
                    <span>Last Sync:</span>
                    <span>{formatTimestamp(status?.sync.lastSyncTime || 0)}</span>
                  </div>
                  <div className="status-item">
                    <span>Messages Synced:</span>
                    <span>{status?.sync.totalMessagesSynced || 0}</span>
                  </div>
                  <div className="status-item">
                    <span>Pending:</span>
                    <span>{status?.sync.pendingUploads || 0}</span>
                  </div>
                </div>
              </div>

              <div className="status-card">
                <div className="card-header">Streaming Status</div>
                <div className="card-content">
                  <div className="status-item">
                    <span>Connected:</span>
                    <span className={status?.streaming.isConnected ? 'text-success' : 'text-error'}>
                      {status?.streaming.isConnected ? 'Yes' : 'No'}
                    </span>
                  </div>
                  <div className="status-item">
                    <span>Active Streams:</span>
                    <span>{status?.streaming.activeStreams || 0}</span>
                  </div>
                  <div className="status-item">
                    <span>Total Processed:</span>
                    <span>{status?.streaming.totalStreamsProcessed || 0}</span>
                  </div>
                  <div className="status-item">
                    <span>Last Activity:</span>
                    <span>{formatTimestamp(status?.streaming.lastActivity || 0)}</span>
                  </div>
                </div>
              </div>

              <div className="status-card">
                <div className="card-header">Statistics</div>
                <div className="card-content">
                  <div className="status-item">
                    <span>Local Sessions:</span>
                    <span>{statistics?.totalLocalSessions || 0}</span>
                  </div>
                  <div className="status-item">
                    <span>Sync Errors:</span>
                    <span className={statistics?.syncErrors > 0 ? 'text-error' : ''}>
                      {statistics?.syncErrors || 0}
                    </span>
                  </div>
                  <div className="status-item">
                    <span>Stream Errors:</span>
                    <span className={statistics?.streamingErrors > 0 ? 'text-error' : ''}>
                      {statistics?.streamingErrors || 0}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* Connectivity Test Results */}
            {connectivityResult && (
              <div className="connectivity-results">
                <div className="card-header">Connectivity Test Results</div>
                <div className="connectivity-status">
                  <div className={`connectivity-item ${connectivityResult.syncConnected ? 'success' : 'error'}`}>
                    <span>Sync Connection:</span>
                    <span>{connectivityResult.syncConnected ? '✅ Connected' : '❌ Failed'}</span>
                  </div>
                  <div className={`connectivity-item ${connectivityResult.streamingConnected ? 'success' : 'error'}`}>
                    <span>Streaming Connection:</span>
                    <span>{connectivityResult.streamingConnected ? '✅ Connected' : '❌ Failed'}</span>
                  </div>
                </div>
                {connectivityResult.errors.length > 0 && (
                  <div className="connectivity-errors">
                    <div className="error-header">Errors:</div>
                    {connectivityResult.errors.map((error: string, index: number) => (
                      <div key={index} className="error-item">{error}</div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {activeTab === 'sessions' && (
          <div className="sessions-tab">
            <div className="sessions-header">
              <h4>Local Sessions ({localSessions.length})</h4>
            </div>
            <div className="sessions-list">
              {localSessions.length === 0 ? (
                <div className="empty-state">No local sessions found</div>
              ) : (
                localSessions.map(session => (
                  <div key={session.id} className="session-item">
                    <div className="session-header">
                      <div className="session-title">{session.title}</div>
                      <div className="session-meta">
                        <span>{session.messages.length} messages</span>
                        <span>{formatTimestamp(session.updatedAt)}</span>
                      </div>
                    </div>
                    <div className="session-preview">
                      {session.messages.slice(-2).map(msg => (
                        <div key={msg.id} className={`message-preview ${msg.role}`}>
                          <span className="role">{msg.role}:</span>
                          <span className="content">
                            {msg.content.substring(0, 100)}
                            {msg.content.length > 100 ? '...' : ''}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        )}

        {activeTab === 'streaming' && (
          <div className="streaming-tab">
            <div className="streaming-header">
              <h4>Real-Time Streaming</h4>
              {onSimulateStream && (
                <button onClick={handleSimulateStream} className="btn btn-outline btn-sm">
                  Simulate Stream
                </button>
              )}
            </div>
            <RealTimeStreamingIndicator
              streamingMessages={streamingMessages}
              isActive={status?.streaming.isConnected || false}
            />
          </div>
        )}

        {activeTab === 'logs' && (
          <div className="logs-tab">
            <div className="logs-header">
              <h4>Error Logs ({errors.length})</h4>
              {errors.length > 0 && (
                <button onClick={onClearErrors} className="btn btn-outline btn-sm">
                  Clear Errors
                </button>
              )}
            </div>
            <div className="logs-list">
              {errors.length === 0 ? (
                <div className="empty-state">No errors logged</div>
              ) : (
                errors.map((error, index) => (
                  <div key={index} className="log-item error">
                    <div className="log-timestamp">{new Date().toLocaleTimeString()}</div>
                    <div className="log-message">{error}</div>
                  </div>
                ))
              )}
            </div>
          </div>
        )}
      </div>

      <style jsx>{`
        .chat-sync-dashboard {
          background: rgba(0, 0, 0, 0.9);
          border: 1px solid rgba(255, 255, 255, 0.2);
          border-radius: 8px;
          padding: 16px;
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          color: white;
          font-size: 13px;
        }

        .dashboard-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 16px;
          padding-bottom: 12px;
          border-bottom: 1px solid rgba(255, 255, 255, 0.1);
        }

        .header-title {
          display: flex;
          align-items: center;
          gap: 12px;
        }

        .header-title h3 {
          margin: 0;
          font-size: 16px;
          font-weight: 600;
        }

        .sync-status {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 4px 8px;
          border-radius: 4px;
          font-size: 11px;
        }

        .sync-status.active {
          background: rgba(0, 255, 136, 0.2);
          color: #00ff88;
        }

        .sync-status.inactive {
          background: rgba(255, 255, 255, 0.1);
          color: #ccc;
        }

        .status-dot {
          width: 6px;
          height: 6px;
          border-radius: 50%;
          background: currentColor;
        }

        .header-controls {
          display: flex;
          gap: 8px;
        }

        .btn {
          padding: 6px 12px;
          border: none;
          border-radius: 4px;
          font-size: 11px;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.2s;
        }

        .btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .btn-primary {
          background: #00ff88;
          color: black;
        }

        .btn-primary:hover:not(:disabled) {
          background: #00cc6a;
        }

        .btn-secondary {
          background: #ff4444;
          color: white;
        }

        .btn-secondary:hover:not(:disabled) {
          background: #cc3333;
        }

        .btn-accent {
          background: #ffa500;
          color: black;
        }

        .btn-accent:hover:not(:disabled) {
          background: #cc8400;
        }

        .btn-outline {
          background: transparent;
          color: white;
          border: 1px solid rgba(255, 255, 255, 0.3);
        }

        .btn-outline:hover:not(:disabled) {
          background: rgba(255, 255, 255, 0.1);
        }

        .btn-sm {
          padding: 4px 8px;
          font-size: 10px;
        }

        .dashboard-tabs {
          display: flex;
          gap: 2px;
          margin-bottom: 16px;
          background: rgba(255, 255, 255, 0.05);
          border-radius: 6px;
          padding: 2px;
        }

        .tab {
          flex: 1;
          padding: 8px 12px;
          background: transparent;
          border: none;
          color: #ccc;
          font-size: 11px;
          font-weight: 500;
          cursor: pointer;
          border-radius: 4px;
          transition: all 0.2s;
          position: relative;
        }

        .tab.active {
          background: rgba(255, 255, 255, 0.1);
          color: white;
        }

        .tab:hover:not(.active) {
          background: rgba(255, 255, 255, 0.05);
        }

        .error-badge {
          position: absolute;
          top: -2px;
          right: -2px;
          background: #ff4444;
          color: white;
          font-size: 8px;
          padding: 1px 4px;
          border-radius: 8px;
          min-width: 14px;
          text-align: center;
        }

        .tab-content {
          min-height: 300px;
        }

        .status-cards {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 12px;
          margin-bottom: 16px;
        }

        .status-card {
          background: rgba(255, 255, 255, 0.05);
          border-radius: 6px;
          padding: 12px;
        }

        .card-header {
          font-weight: 600;
          margin-bottom: 8px;
          color: #00ff88;
          font-size: 12px;
        }

        .card-content {
          space-y: 6px;
        }

        .status-item {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 6px;
        }

        .text-success {
          color: #00ff88;
        }

        .text-error {
          color: #ff4444;
        }

        .connectivity-results {
          background: rgba(255, 255, 255, 0.05);
          border-radius: 6px;
          padding: 12px;
        }

        .connectivity-status {
          margin: 8px 0;
        }

        .connectivity-item {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 6px;
        }

        .connectivity-item.success {
          color: #00ff88;
        }

        .connectivity-item.error {
          color: #ff4444;
        }

        .connectivity-errors {
          margin-top: 12px;
          padding-top: 8px;
          border-top: 1px solid rgba(255, 255, 255, 0.1);
        }

        .error-header {
          font-weight: 500;
          margin-bottom: 6px;
          color: #ff4444;
        }

        .error-item {
          background: rgba(255, 68, 68, 0.1);
          padding: 4px 8px;
          border-radius: 4px;
          margin-bottom: 4px;
          font-size: 11px;
        }

        .sessions-header, .streaming-header, .logs-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 12px;
        }

        .sessions-header h4, .streaming-header h4, .logs-header h4 {
          margin: 0;
          font-size: 14px;
          font-weight: 600;
        }

        .sessions-list, .logs-list {
          max-height: 400px;
          overflow-y: auto;
        }

        .session-item {
          background: rgba(255, 255, 255, 0.05);
          border-radius: 6px;
          padding: 12px;
          margin-bottom: 8px;
        }

        .session-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 8px;
        }

        .session-title {
          font-weight: 500;
          font-size: 12px;
        }

        .session-meta {
          display: flex;
          gap: 12px;
          font-size: 10px;
          color: #ccc;
        }

        .session-preview {
          space-y: 4px;
        }

        .message-preview {
          display: flex;
          gap: 6px;
          font-size: 10px;
          margin-bottom: 4px;
        }

        .message-preview .role {
          font-weight: 500;
          min-width: 40px;
        }

        .message-preview.user .role {
          color: #00ff88;
        }

        .message-preview.assistant .role {
          color: #ffa500;
        }

        .message-preview .content {
          color: #ddd;
          line-height: 1.3;
        }

        .log-item {
          display: flex;
          gap: 8px;
          padding: 8px;
          border-radius: 4px;
          margin-bottom: 4px;
          font-size: 11px;
        }

        .log-item.error {
          background: rgba(255, 68, 68, 0.1);
          border-left: 3px solid #ff4444;
        }

        .log-timestamp {
          color: #888;
          min-width: 80px;
          font-size: 10px;
        }

        .log-message {
          flex: 1;
          line-height: 1.3;
        }

        .empty-state {
          text-align: center;
          color: #888;
          padding: 40px 20px;
          font-style: italic;
        }
      `}</style>
    </div>
  );
};

export default ChatSyncDashboard;